import { rest } from "msw";

export const handlers = [
  rest.get("https://api.opendota.com/api/heroStats", (req, res, ctx) => {
    return res(
      ctx.json([
        {
          id: 1,
          name: "npc_dota_hero_antimage",
          localized_name: "Anti-Mage",
          primary_attr: "agi",
          attack_type: "Melee",
          roles: ["Carry", "Escape", "Nuker"],
          img: "/apps/dota2/images/heroes/antimage_full.png?",
          icon: "/apps/dota2/images/heroes/antimage_icon.png",
          attack_range: 150,
          move_speed: 310,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 2,
          hero_id: 1,
        },
        {
          id: 2,
          name: "npc_dota_hero_axe",
          localized_name: "Axe",
          primary_attr: "str",
          attack_type: "Melee",
          roles: ["Initiator", "Durable", "Disabler", "Jungler"],
          img: "/apps/dota2/images/heroes/axe_full.png?",
          icon: "/apps/dota2/images/heroes/axe_icon.png",
          attack_range: 150,
          move_speed: 310,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 2,
          hero_id: 2,
        },
        {
          id: 3,
          name: "npc_dota_hero_bane",
          localized_name: "Bane",
          primary_attr: "int",
          attack_type: "Ranged",
          roles: ["Support", "Disabler", "Nuker", "Durable"],
          img: "/apps/dota2/images/heroes/bane_full.png?",
          icon: "/apps/dota2/images/heroes/bane_icon.png",
          attack_range: 400,
          move_speed: 305,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 4,
          hero_id: 3,
        },
        {
          id: 4,
          name: "npc_dota_hero_bloodseeker",
          localized_name: "Bloodseeker",
          primary_attr: "agi",
          attack_type: "Melee",
          roles: ["Carry", "Disabler", "Jungler", "Nuker", "Initiator"],
          img: "/apps/dota2/images/heroes/bloodseeker_full.png?",
          icon: "/apps/dota2/images/heroes/bloodseeker_icon.png",
          attack_range: 150,
          move_speed: 300,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 2,
          hero_id: 4,
        },
        {
          id: 5,
          name: "npc_dota_hero_crystal_maiden",
          localized_name: "Crystal Maiden",
          primary_attr: "int",
          attack_type: "Ranged",
          roles: ["Support", "Disabler", "Nuker", "Jungler"],
          img: "/apps/dota2/images/heroes/crystal_maiden_full.png?",
          icon: "/apps/dota2/images/heroes/crystal_maiden_icon.png",
          attack_range: 600,
          move_speed: 280,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 2,
          hero_id: 5,
        },
        {
          id: 6,
          name: "npc_dota_hero_drow_ranger",
          localized_name: "Drow Ranger",
          primary_attr: "agi",
          attack_type: "Ranged",
          roles: ["Carry", "Disabler", "Pusher"],
          img: "/apps/dota2/images/heroes/drow_ranger_full.png?",
          icon: "/apps/dota2/images/heroes/drow_ranger_icon.png",
          attack_range: 625,
          move_speed: 290,
          turn_rate: 0.7,
          cm_enabled: true,
          legs: 2,
          hero_id: 6,
        },
        {
          id: 7,
          name: "npc_dota_hero_earthshaker",
          localized_name: "Earthshaker",
          primary_attr: "str",
          attack_type: "Melee",
          roles: ["Support", "Initiator", "Disabler", "Nuker"],
          img: "/apps/dota2/images/heroes/earthshaker_full.png?",
          icon: "/apps/dota2/images/heroes/earthshaker_icon.png",
          attack_range: 150,
          move_speed: 310,
          turn_rate: 0.9,
          cm_enabled: true,
          legs: 2,
          hero_id: 7,
        },
        {
          id: 8,
          name: "npc_dota_hero_juggernaut",
          localized_name: "Juggernaut",
          primary_attr: "agi",
          attack_type: "Melee",
          roles: ["Carry", "Pusher", "Escape"],
          img: "/apps/dota2/images/heroes/juggernaut_full.png?",
          icon: "/apps/dota2/images/heroes/juggernaut_icon.png",
          attack_range: 150,
          move_speed: 305,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 2,
          hero_id: 8,
        },
        {
          id: 9,
          name: "npc_dota_hero_mirana",
          localized_name: "Mirana",
          primary_attr: "agi",
          attack_type: "Ranged",
          roles: ["Carry", "Support", "Escape", "Nuker", "Disabler"],
          img: "/apps/dota2/images/heroes/mirana_full.png?",
          icon: "/apps/dota2/images/heroes/mirana_icon.png",
          attack_range: 630,
          move_speed: 290,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 2,
          hero_id: 9,
        },
        {
          id: 10,
          name: "npc_dota_hero_morphling",
          localized_name: "Morphling",
          primary_attr: "agi",
          attack_type: "Ranged",
          roles: ["Carry", "Escape", "Durable", "Nuker", "Disabler"],
          img: "/apps/dota2/images/heroes/morphling_full.png?",
          icon: "/apps/dota2/images/heroes/morphling_icon.png",
          attack_range: 350,
          move_speed: 280,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 0,
          hero_id: 10,
        },
        {
          id: 11,
          name: "npc_dota_hero_nevermore",
          localized_name: "Shadow Fiend",
          primary_attr: "agi",
          attack_type: "Ranged",
          roles: ["Carry", "Nuker"],
          img: "/apps/dota2/images/heroes/nevermore_full.png?",
          icon: "/apps/dota2/images/heroes/nevermore_icon.png",
          attack_range: 500,
          move_speed: 305,
          turn_rate: 1,
          cm_enabled: true,
          legs: 0,
          hero_id: 11,
        },
        {
          id: 12,
          name: "npc_dota_hero_phantom_lancer",
          localized_name: "Phantom Lancer",
          primary_attr: "agi",
          attack_type: "Melee",
          roles: ["Carry", "Escape", "Pusher", "Nuker"],
          img: "/apps/dota2/images/heroes/phantom_lancer_full.png?",
          icon: "/apps/dota2/images/heroes/phantom_lancer_icon.png",
          attack_range: 150,
          move_speed: 290,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 2,
          hero_id: 12,
        },
        {
          id: 13,
          name: "npc_dota_hero_puck",
          localized_name: "Puck",
          primary_attr: "int",
          attack_type: "Ranged",
          roles: ["Initiator", "Disabler", "Escape", "Nuker"],
          img: "/apps/dota2/images/heroes/puck_full.png?",
          icon: "/apps/dota2/images/heroes/puck_icon.png",
          attack_range: 550,
          move_speed: 290,
          turn_rate: 0.8,
          cm_enabled: true,
          legs: 2,
          hero_id: 13,
        },
        {
          id: 14,
          name: "npc_dota_hero_pudge",
          localized_name: "Pudge",
          primary_attr: "str",
          attack_type: "Melee",
          roles: ["Disabler", "Initiator", "Durable", "Nuker"],
          img: "/apps/dota2/images/heroes/pudge_full.png?",
          icon: "/apps/dota2/images/heroes/pudge_icon.png",
          attack_range: 150,
          move_speed: 280,
          turn_rate: 0.7,
          cm_enabled: true,
          legs: 2,
          hero_id: 14,
        },
        {
          id: 15,
          name: "npc_dota_hero_razor",
          localized_name: "Razor",
          primary_attr: "agi",
          attack_type: "Ranged",
          roles: ["Carry", "Durable", "Nuker", "Pusher"],
          img: "/apps/dota2/images/heroes/razor_full.png?",
          icon: "/apps/dota2/images/heroes/razor_icon.png",
          attack_range: 475,
          move_speed: 290,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 0,
          hero_id: 15,
        },
        {
          id: 16,
          name: "npc_dota_hero_sand_king",
          localized_name: "Sand King",
          primary_attr: "str",
          attack_type: "Melee",
          roles: [
            "Initiator",
            "Disabler",
            "Support",
            "Nuker",
            "Escape",
            "Jungler",
          ],
          img: "/apps/dota2/images/heroes/sand_king_full.png?",
          icon: "/apps/dota2/images/heroes/sand_king_icon.png",
          attack_range: 150,
          move_speed: 290,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 6,
          hero_id: 16,
        },
        {
          id: 17,
          name: "npc_dota_hero_storm_spirit",
          localized_name: "Storm Spirit",
          primary_attr: "int",
          attack_type: "Ranged",
          roles: ["Carry", "Escape", "Nuker", "Initiator", "Disabler"],
          img: "/apps/dota2/images/heroes/storm_spirit_full.png?",
          icon: "/apps/dota2/images/heroes/storm_spirit_icon.png",
          attack_range: 480,
          move_speed: 285,
          turn_rate: 0.8,
          cm_enabled: true,
          legs: 2,
          hero_id: 17,
        },
        {
          id: 18,
          name: "npc_dota_hero_sven",
          localized_name: "Sven",
          primary_attr: "str",
          attack_type: "Melee",
          roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
          img: "/apps/dota2/images/heroes/sven_full.png?",
          icon: "/apps/dota2/images/heroes/sven_icon.png",
          attack_range: 150,
          move_speed: 325,
          turn_rate: 0.6,
          cm_enabled: true,
          legs: 2,
        },
        {
          id: 19,
          name: "npc_dota_hero_tiny",
          localized_name: "Tiny",
          primary_attr: "str",
          attack_type: "Melee",
          roles: [
            "Carry",
            "Nuker",
            "Pusher",
            "Initiator",
            "Durable",
            "Disabler",
          ],
          img: "/apps/dota2/images/heroes/tiny_full.png?",
          icon: "/apps/dota2/images/heroes/tiny_icon.png",
          attack_range: 150,
          move_speed: 300,
          turn_rate: 0.5,
          cm_enabled: true,
          legs: 2,
          hero_id: 19,
        },
      ])
    );
  }),
];
